encoder:
  - layer: [1,24,3,2,1]
  - act: "ReLU"
  - layer: [24,48,3,2,1]
  - act: "ReLU"
  - layer: [48,96,5,1,0]
  - act: "ReLU"
decoder:
  - layer: [96,48,5,1,0,0]
  - act: "ReLU"
  - layer: [48,24,3,2,1,1]
  - act: "ReLU"
  - layer: [24,1,3,2,1,1]
  - act: "Tanh"
criterion: 
  loss: "MSELoss"
  final_loss: 0.000276
epochs: 100
seed: 123
batch_size: 64
optimizer: 
  Adam: 
    learning_rate: 0.001
    weight_decay: 0.00001