encoder:
  - layer: [1,8,3,2,1]
  - act: "ReLU"
  - layer: [8,32,3,2,1]
  - act: "ReLU"
  - layer: [32,128,5,1,0]
  - act: "ReLU"
decoder:
  - layer: [128,32,5,1,0,0]
  - act: "ReLU"
  - layer: [32,8,3,2,1,1]
  - act: "ReLU"
  - layer: [8,1,3,2,1,1]
  - act: "Tanh"
criterion: 
  loss: "MSELoss"
  final_loss: 0.000276
epochs: 100
seed: 123
batch_size: 64
optimizer: 
  Adam: 
    learning_rate: 0.001
    weight_decay: 0.00001