encoder:
  - layer: [1,18,3,2,1]
  - act: "ReLU"
  - layer: [18,72,3,2,1]
  - act: "ReLU"
  - layer: [72,144,5,1,0]
  - act: "ReLU"
decoder:
  - layer: [144,72,5,1,0,0]
  - act: "ReLU"
  - layer: [72,18,3,2,1,1]
  - act: "ReLU"
  - layer: [18,1,3,2,1,1]
  - act: "Tanh"
criterion: 
  loss: "MSELoss"
  final_loss: 0.000276
epochs: 100
seed: 123
batch_size: 64
optimizer: 
  Adam: 
    learning_rate: 0.001
    weight_decay: 0.00001